# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-zcu104-ddr4"
BBFILE_PATTERN_meta-zcu104-ddr4 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-zcu104-ddr4 = "6"

LAYERDEPENDS_meta-zcu104-ddr4 = "core"
LAYERSERIES_COMPAT_meta-zcu104-ddr4 = "scarthgap"
