####################################################################################
# ZCU104 PL DDR4 SODIMM (socket J1) pin constraints
# Target device : xczu7ev-ffvc1156-2-e
# Controller    : ddr4_sdram   (external IPI interface -> ports "ddr4_sdram_*")
# Source        : UG1267 (v1.1) Table 3-4 (socket J1 pinout) + Table 3-13 (CLK_300)
#
# --------------------------------------------------------------------------------
# SCOPE / HOW TO USE
# --------------------------------------------------------------------------------
# * This file works for BOTH x8 and x16 SODIMM organizations. The socket wiring is
#   identical; the only difference is which ports the DDR4 MIG instantiates:
#       - x8  module (e.g. Micron MTA8ATF51264HZ) : bank group = bg[1:0]  (2 bits)
#       - x16 module (e.g. Samsung M471A5244CB0)  : bank group = bg[0]    (1 bit)
#   The file is x16-SAFE by default. For an x8 build, uncomment the ONE line in the
#   "BANK GROUP - x8 ONLY" block below.
#
# * Both target modules are SINGLE RANK. Rank-1 signals (cs1/cke1/odt1/ck1) are
#   wired at the socket but left commented; uncomment the "DUAL RANK" block only if
#   you fit a 2-rank module and configure MIG for 2 ranks.
#
# * If the interface in your block design is NOT named "ddr4_sdram", replace the
#   "ddr4_sdram_" prefix throughout (e.g. sed s/ddr4_sdram_/c0_ddr4_/g).
#
# * SANCTIONED FLOW: for a Memory IP / MIG design the physical constraints
#   (PACKAGE_PIN, IOSTANDARD, DCI, INTERNAL_VREF) are normally generated by the IP
#   from the board file. Treat this hand-written file as a reference/stopgap. If you
#   see IOSTANDARD/DCI conflict warnings, the IP is already setting them - in that
#   case keep only the PACKAGE_PIN half of each line, or omit this file entirely and
#   let Memory IP generate constraints from the ZCU104 board flow.
####################################################################################


####################################################################################
# SYSTEM / MEMORY REFERENCE CLOCK  (300 MHz differential, bank 66 GC pins)
# --------------------------------------------------------------------------------
# UG1267 Table 3-13: CLK_300_C_P = AH12, CLK_300_C_N = AJ12.
# NOTE: this is the MIG c0_sys_clk input, NOT part of the SODIMM interface. It is
# included because a wrong sys_clk LOC (e.g. AH18, which is actually DM0) prevents
# calibration entirely. Rename the port below to match your top-level sys_clk port.
####################################################################################
set_property -dict {PACKAGE_PIN AH12 IOSTANDARD DIFF_SSTL12} [get_ports {c0_sys_clk_p}]
set_property -dict {PACKAGE_PIN AJ12 IOSTANDARD DIFF_SSTL12} [get_ports {c0_sys_clk_n}]


####################################################################################
# ADDRESS  (A0..A13, plus A14/A15/A16 which carry WE_n/CAS_n/RAS_n in DDR4)
####################################################################################
set_property -dict {PACKAGE_PIN AH8  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[0]}]
set_property -dict {PACKAGE_PIN AG8  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[1]}]
set_property -dict {PACKAGE_PIN AF8  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[2]}]
set_property -dict {PACKAGE_PIN AG10 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[3]}]
set_property -dict {PACKAGE_PIN AG11 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[4]}]
set_property -dict {PACKAGE_PIN AH9  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[5]}]
set_property -dict {PACKAGE_PIN AG9  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[6]}]
set_property -dict {PACKAGE_PIN AH13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[7]}]
set_property -dict {PACKAGE_PIN AK10 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[8]}]
set_property -dict {PACKAGE_PIN AJ10 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[9]}]
set_property -dict {PACKAGE_PIN AL8  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[10]}]
set_property -dict {PACKAGE_PIN AK8  IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[11]}]
set_property -dict {PACKAGE_PIN AL12 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[12]}]
set_property -dict {PACKAGE_PIN AK12 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[13]}]
set_property -dict {PACKAGE_PIN AC12 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[14]}] ;# WE_n/A14
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[15]}] ;# CAS_n/A15
set_property -dict {PACKAGE_PIN AF11 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[16]}] ;# RAS_n/A16


####################################################################################
# BANK ADDRESS / BANK GROUP
####################################################################################
set_property -dict {PACKAGE_PIN AL10 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_ba[0]}]
set_property -dict {PACKAGE_PIN AL11 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_ba[1]}]
set_property -dict {PACKAGE_PIN AE14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_bg[0]}]

# ---- BANK GROUP - x8 ONLY --------------------------------------------------------
# Uncomment for an x8-organization module (bg[1:0]). Leave commented for x16.
# set_property -dict {PACKAGE_PIN AE13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_bg[1]}]
# ----------------------------------------------------------------------------------


####################################################################################
# COMMAND / CONTROL  (rank 0)
####################################################################################
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_act_n}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_cke[0]}]
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_cs_n[0]}]
set_property -dict {PACKAGE_PIN AF10 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_odt[0]}]

# reset_n is LVCMOS12 (no DCI)
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS12 DRIVE 8} [get_ports {ddr4_sdram_reset_n}]


####################################################################################
# MEMORY CLOCK  (rank 0)  --  DIFFERENTIAL
# NOTE: net-name polarity used (AH11 = CK0_T = P side, AJ11 = CK0_C = N side). The
# UG1267 SODIMM-pin-name column has a T/C label swap on these rows; if the pair is
# actually inverted, Vivado will emit a differential-pair DRC error at place time
# (it will not mis-train silently) - swap the two LOCs if that fires.
####################################################################################
set_property -dict {PACKAGE_PIN AH11 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_sdram_ck_t[0]}]
set_property -dict {PACKAGE_PIN AJ11 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_sdram_ck_c[0]}]


####################################################################################
# DATA  (DQ[63:0])  --  POD12_DCI
# Byte-lane grouping (DQ->DQS) is what matters; individual DQ bits within a lane may
# be swapped freely by the MIG (per-bit deskew). Mapping below follows Table 3-4.
####################################################################################
# --- Byte 0 (DQS0) ---
set_property -dict {PACKAGE_PIN AG14 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[0]}]
set_property -dict {PACKAGE_PIN AG15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[1]}]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[2]}]
set_property -dict {PACKAGE_PIN AF16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[3]}]
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[4]}]
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[5]}]
set_property -dict {PACKAGE_PIN AG18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[6]}]
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[7]}]
# --- Byte 1 (DQS1) ---
set_property -dict {PACKAGE_PIN AD16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[8]}]
set_property -dict {PACKAGE_PIN AD17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[9]}]
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[10]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[11]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[12]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[13]}]
set_property -dict {PACKAGE_PIN AC16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[14]}]
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[15]}]
# --- Byte 2 (DQS2) ---
set_property -dict {PACKAGE_PIN AJ15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[16]}]
set_property -dict {PACKAGE_PIN AJ16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[17]}]
set_property -dict {PACKAGE_PIN AK17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[18]}]
set_property -dict {PACKAGE_PIN AJ17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[19]}]
set_property -dict {PACKAGE_PIN AL18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[20]}]
set_property -dict {PACKAGE_PIN AK18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[21]}]
set_property -dict {PACKAGE_PIN AL15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[22]}]
set_property -dict {PACKAGE_PIN AL16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[23]}]
# --- Byte 3 (DQS3) ---
set_property -dict {PACKAGE_PIN AN16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[24]}]
set_property -dict {PACKAGE_PIN AN17 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[25]}]
set_property -dict {PACKAGE_PIN AP15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[26]}]
set_property -dict {PACKAGE_PIN AP16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[27]}]
set_property -dict {PACKAGE_PIN AN18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[28]}]
set_property -dict {PACKAGE_PIN AM18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[29]}]
set_property -dict {PACKAGE_PIN AP13 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[30]}]
set_property -dict {PACKAGE_PIN AN13 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[31]}]
# --- Byte 4 (DQS4) ---
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[32]}]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[33]}]
set_property -dict {PACKAGE_PIN AD19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[34]}]
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[35]}]
set_property -dict {PACKAGE_PIN AE20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[36]}]
set_property -dict {PACKAGE_PIN AD20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[37]}]
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[38]}]
set_property -dict {PACKAGE_PIN AB19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[39]}]
# --- Byte 5 (DQS5) ---
set_property -dict {PACKAGE_PIN AE24 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[40]}]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[41]}]
set_property -dict {PACKAGE_PIN AF22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[42]}]
set_property -dict {PACKAGE_PIN AF21 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[43]}]
set_property -dict {PACKAGE_PIN AG20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[44]}]
set_property -dict {PACKAGE_PIN AG19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[45]}]
set_property -dict {PACKAGE_PIN AH21 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[46]}]
set_property -dict {PACKAGE_PIN AG21 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[47]}]
# --- Byte 6 (DQS6) ---
set_property -dict {PACKAGE_PIN AJ22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[48]}]
set_property -dict {PACKAGE_PIN AJ21 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[49]}]
set_property -dict {PACKAGE_PIN AK20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[50]}]
set_property -dict {PACKAGE_PIN AJ20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[51]}]
set_property -dict {PACKAGE_PIN AK19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[52]}]
set_property -dict {PACKAGE_PIN AJ19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[53]}]
set_property -dict {PACKAGE_PIN AL23 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[54]}]
set_property -dict {PACKAGE_PIN AL22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[55]}]
# --- Byte 7 (DQS7) ---
set_property -dict {PACKAGE_PIN AN23 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[56]}]
set_property -dict {PACKAGE_PIN AM23 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[57]}]
set_property -dict {PACKAGE_PIN AP23 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[58]}]
set_property -dict {PACKAGE_PIN AN22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[59]}]
set_property -dict {PACKAGE_PIN AP22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[60]}]
set_property -dict {PACKAGE_PIN AP21 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[61]}]
set_property -dict {PACKAGE_PIN AN19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[62]}]
set_property -dict {PACKAGE_PIN AM19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[63]}]


####################################################################################
# DATA STROBES  (DQS[7:0])  --  DIFF_POD12_DCI
####################################################################################
set_property -dict {PACKAGE_PIN AH14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[0]}]
set_property -dict {PACKAGE_PIN AJ14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[0]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[1]}]
set_property -dict {PACKAGE_PIN AK15 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[2]}]
set_property -dict {PACKAGE_PIN AK14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[2]}]
set_property -dict {PACKAGE_PIN AM14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[3]}]
set_property -dict {PACKAGE_PIN AN14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[3]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[4]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[4]}]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[5]}]
set_property -dict {PACKAGE_PIN AG23 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[5]}]
set_property -dict {PACKAGE_PIN AK22 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[6]}]
set_property -dict {PACKAGE_PIN AK23 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[6]}]
set_property -dict {PACKAGE_PIN AM21 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[7]}]
set_property -dict {PACKAGE_PIN AN21 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[7]}]


####################################################################################
# DATA MASK  (DM_n[7:0])  --  POD12_DCI
# --------------------------------------------------------------------------------
# Pins are wired at the socket for both organizations, BUT the port only exists in a
# data-mask MIG config, which implies an x8 device (DDR4 x16 devices have no DM):
#   - x8  module, DM enabled  : port is ddr4_sdram_dm_n[7:0]  -> keep these 8 lines.
#   - x16 module              : reconfigure MIG to the x16 part; DM is unavailable, so
#                               NO dm_n ports are generated -> COMMENT OUT all 8 lines.
# (If a config uses DM+DBI, the port is instead named ddr4_sdram_dm_dbi_n[7:0].)
####################################################################################
set_property -dict {PACKAGE_PIN AH18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[0]}]
set_property -dict {PACKAGE_PIN AD15 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[1]}]
set_property -dict {PACKAGE_PIN AM16 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[2]}]
set_property -dict {PACKAGE_PIN AP18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[3]}]
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[4]}]
set_property -dict {PACKAGE_PIN AH22 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[5]}]
set_property -dict {PACKAGE_PIN AL20 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[6]}]
set_property -dict {PACKAGE_PIN AP19 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[7]}]


####################################################################################
# OPTIONAL: C/A PARITY + ALERT  (only if enabled in MIG)
####################################################################################
# set_property -dict {PACKAGE_PIN AC13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_parity}]
# set_property -dict {PACKAGE_PIN AF13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_alert_n}]


####################################################################################
# OPTIONAL: DUAL-RANK signals (rank 1) -- both recommended modules are SINGLE RANK.
# Uncomment ONLY for a 2-rank module configured as 2 ranks in MIG.
####################################################################################
# set_property -dict {PACKAGE_PIN AL13 IOSTANDARD SSTL12_DCI}      [get_ports {ddr4_sdram_cke[1]}]
# set_property -dict {PACKAGE_PIN AM13 IOSTANDARD SSTL12_DCI}      [get_ports {ddr4_sdram_cs_n[1]}]
# set_property -dict {PACKAGE_PIN AK13 IOSTANDARD SSTL12_DCI}      [get_ports {ddr4_sdram_odt[1]}]
# set_property -dict {PACKAGE_PIN AJ9  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_sdram_ck_t[1]}]
# set_property -dict {PACKAGE_PIN AK9  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_sdram_ck_c[1]}]
