# Clock
set_property -dict {PACKAGE_PIN AH18 IOSTANDARD DIFF_SSTL12} [get_ports {CLK_300_P}]
set_property -dict {PACKAGE_PIN AH17 IOSTANDARD DIFF_SSTL12} [get_ports {CLK_300_N}]

# UART2
set_property PACKAGE_PIN C19 [get_ports {uart2_PL_TX}]
set_property PACKAGE_PIN A20 [get_ports {uart2_PL_RX}]

# I2C1
set_property -dict {PACKAGE_PIN N12 IOSTANDARD LVCMOS33} [get_ports {IIC1_SCL_MAIN}]
set_property -dict {PACKAGE_PIN P12 IOSTANDARD LVCMOS33} [get_ports {IIC1_SDA_MAIN}]

# DDR4 Address
set_property PACKAGE_PIN AH16 [get_ports {ddr4_sdram_adr[0]}]
set_property PACKAGE_PIN AG14 [get_ports {ddr4_sdram_adr[1]}]
set_property PACKAGE_PIN AG15 [get_ports {ddr4_sdram_adr[2]}]
set_property PACKAGE_PIN AF15 [get_ports {ddr4_sdram_adr[3]}]
set_property PACKAGE_PIN AF16 [get_ports {ddr4_sdram_adr[4]}]
set_property PACKAGE_PIN AJ14 [get_ports {ddr4_sdram_adr[5]}]
set_property PACKAGE_PIN AH14 [get_ports {ddr4_sdram_adr[6]}]
set_property PACKAGE_PIN AF17 [get_ports {ddr4_sdram_adr[7]}]
set_property PACKAGE_PIN AK17 [get_ports {ddr4_sdram_adr[8]}]
set_property PACKAGE_PIN AJ17 [get_ports {ddr4_sdram_adr[9]}]
set_property PACKAGE_PIN AK14 [get_ports {ddr4_sdram_adr[10]}]
set_property PACKAGE_PIN AK15 [get_ports {ddr4_sdram_adr[11]}]
set_property PACKAGE_PIN AL18 [get_ports {ddr4_sdram_adr[12]}]
set_property PACKAGE_PIN AK18 [get_ports {ddr4_sdram_adr[13]}]
set_property PACKAGE_PIN AA16 [get_ports {ddr4_sdram_adr[14]}]
set_property PACKAGE_PIN AA14 [get_ports {ddr4_sdram_adr[15]}]
set_property PACKAGE_PIN AD15 [get_ports {ddr4_sdram_adr[16]}]

# DDR4 Bank
set_property PACKAGE_PIN AL15 [get_ports {ddr4_sdram_ba[0]}]
set_property PACKAGE_PIN AL16 [get_ports {ddr4_sdram_ba[1]}]
set_property PACKAGE_PIN AC16 [get_ports {ddr4_sdram_bg[0]}]
set_property PACKAGE_PIN AB16 [get_ports {ddr4_sdram_bg[1]}]

# DDR4 Clock
set_property PACKAGE_PIN AF18 [get_ports {ddr4_sdram_ck_t[0]}]
set_property PACKAGE_PIN AG18 [get_ports {ddr4_sdram_ck_c[0]}]
set_property PACKAGE_PIN AJ16 [get_ports {ddr4_sdram_ck_t[1]}]
set_property PACKAGE_PIN AJ15 [get_ports {ddr4_sdram_ck_c[1]}]

# DDR4 Control
set_property PACKAGE_PIN AC17 [get_ports {ddr4_sdram_act_n}]
set_property PACKAGE_PIN AD17 [get_ports {ddr4_sdram_cke[0]}]
set_property PACKAGE_PIN AM15 [get_ports {ddr4_sdram_cke[1]}]
set_property PACKAGE_PIN AA15 [get_ports {ddr4_sdram_cs_n[0]}]
set_property PACKAGE_PIN AL17 [get_ports {ddr4_sdram_cs_n[1]}]
set_property PACKAGE_PIN AE15 [get_ports {ddr4_sdram_odt[0]}]
set_property PACKAGE_PIN AM16 [get_ports {ddr4_sdram_odt[1]}]

# DDR4 Data
set_property PACKAGE_PIN AE24 [get_ports {ddr4_sdram_dq[0]}]
set_property PACKAGE_PIN AE23 [get_ports {ddr4_sdram_dq[1]}]
set_property PACKAGE_PIN AF22 [get_ports {ddr4_sdram_dq[2]}]
set_property PACKAGE_PIN AF21 [get_ports {ddr4_sdram_dq[3]}]
set_property PACKAGE_PIN AG20 [get_ports {ddr4_sdram_dq[4]}]
set_property PACKAGE_PIN AG19 [get_ports {ddr4_sdram_dq[5]}]
set_property PACKAGE_PIN AH21 [get_ports {ddr4_sdram_dq[6]}]
set_property PACKAGE_PIN AG21 [get_ports {ddr4_sdram_dq[7]}]
set_property PACKAGE_PIN AA20 [get_ports {ddr4_sdram_dq[8]}]
set_property PACKAGE_PIN AA19 [get_ports {ddr4_sdram_dq[9]}]
set_property PACKAGE_PIN AD19 [get_ports {ddr4_sdram_dq[10]}]
set_property PACKAGE_PIN AC18 [get_ports {ddr4_sdram_dq[11]}]
set_property PACKAGE_PIN AE20 [get_ports {ddr4_sdram_dq[12]}]
set_property PACKAGE_PIN AD20 [get_ports {ddr4_sdram_dq[13]}]
set_property PACKAGE_PIN AC19 [get_ports {ddr4_sdram_dq[14]}]
set_property PACKAGE_PIN AB19 [get_ports {ddr4_sdram_dq[15]}]
set_property PACKAGE_PIN AJ22 [get_ports {ddr4_sdram_dq[16]}]
set_property PACKAGE_PIN AJ21 [get_ports {ddr4_sdram_dq[17]}]
set_property PACKAGE_PIN AK20 [get_ports {ddr4_sdram_dq[18]}]
set_property PACKAGE_PIN AJ20 [get_ports {ddr4_sdram_dq[19]}]
set_property PACKAGE_PIN AK19 [get_ports {ddr4_sdram_dq[20]}]
set_property PACKAGE_PIN AJ19 [get_ports {ddr4_sdram_dq[21]}]
set_property PACKAGE_PIN AL23 [get_ports {ddr4_sdram_dq[22]}]
set_property PACKAGE_PIN AL22 [get_ports {ddr4_sdram_dq[23]}]
set_property PACKAGE_PIN AN23 [get_ports {ddr4_sdram_dq[24]}]
set_property PACKAGE_PIN AM23 [get_ports {ddr4_sdram_dq[25]}]
set_property PACKAGE_PIN AP23 [get_ports {ddr4_sdram_dq[26]}]
set_property PACKAGE_PIN AN22 [get_ports {ddr4_sdram_dq[27]}]
set_property PACKAGE_PIN AP22 [get_ports {ddr4_sdram_dq[28]}]
set_property PACKAGE_PIN AP21 [get_ports {ddr4_sdram_dq[29]}]
set_property PACKAGE_PIN AN19 [get_ports {ddr4_sdram_dq[30]}]
set_property PACKAGE_PIN AM19 [get_ports {ddr4_sdram_dq[31]}]
set_property PACKAGE_PIN AC13 [get_ports {ddr4_sdram_dq[32]}]
set_property PACKAGE_PIN AB13 [get_ports {ddr4_sdram_dq[33]}]
set_property PACKAGE_PIN AF12 [get_ports {ddr4_sdram_dq[34]}]
set_property PACKAGE_PIN AE12 [get_ports {ddr4_sdram_dq[35]}]
set_property PACKAGE_PIN AF13 [get_ports {ddr4_sdram_dq[36]}]
set_property PACKAGE_PIN AE13 [get_ports {ddr4_sdram_dq[37]}]
set_property PACKAGE_PIN AE14 [get_ports {ddr4_sdram_dq[38]}]
set_property PACKAGE_PIN AD14 [get_ports {ddr4_sdram_dq[39]}]
set_property PACKAGE_PIN AG8  [get_ports {ddr4_sdram_dq[40]}]
set_property PACKAGE_PIN AF8  [get_ports {ddr4_sdram_dq[41]}]
set_property PACKAGE_PIN AG10 [get_ports {ddr4_sdram_dq[42]}]
set_property PACKAGE_PIN AG11 [get_ports {ddr4_sdram_dq[43]}]
set_property PACKAGE_PIN AH13 [get_ports {ddr4_sdram_dq[44]}]
set_property PACKAGE_PIN AG13 [get_ports {ddr4_sdram_dq[45]}]
set_property PACKAGE_PIN AJ11 [get_ports {ddr4_sdram_dq[46]}]
set_property PACKAGE_PIN AH11 [get_ports {ddr4_sdram_dq[47]}]
set_property PACKAGE_PIN AK9  [get_ports {ddr4_sdram_dq[48]}]
set_property PACKAGE_PIN AJ9  [get_ports {ddr4_sdram_dq[49]}]
set_property PACKAGE_PIN AK10 [get_ports {ddr4_sdram_dq[50]}]
set_property PACKAGE_PIN AJ10 [get_ports {ddr4_sdram_dq[51]}]
set_property PACKAGE_PIN AL12 [get_ports {ddr4_sdram_dq[52]}]
set_property PACKAGE_PIN AK12 [get_ports {ddr4_sdram_dq[53]}]
set_property PACKAGE_PIN AL10 [get_ports {ddr4_sdram_dq[54]}]
set_property PACKAGE_PIN AL11 [get_ports {ddr4_sdram_dq[55]}]
set_property PACKAGE_PIN AM8  [get_ports {ddr4_sdram_dq[56]}]
set_property PACKAGE_PIN AM9  [get_ports {ddr4_sdram_dq[57]}]
set_property PACKAGE_PIN AM10 [get_ports {ddr4_sdram_dq[58]}]
set_property PACKAGE_PIN AM11 [get_ports {ddr4_sdram_dq[59]}]
set_property PACKAGE_PIN AP11 [get_ports {ddr4_sdram_dq[60]}]
set_property PACKAGE_PIN AN11 [get_ports {ddr4_sdram_dq[61]}]
set_property PACKAGE_PIN AP9  [get_ports {ddr4_sdram_dq[62]}]
set_property PACKAGE_PIN AP10 [get_ports {ddr4_sdram_dq[63]}]

# DDR4 Data Strobe
set_property PACKAGE_PIN AF23 [get_ports {ddr4_sdram_dqs_t[0]}]
set_property PACKAGE_PIN AG23 [get_ports {ddr4_sdram_dqs_c[0]}]
set_property PACKAGE_PIN AA18 [get_ports {ddr4_sdram_dqs_t[1]}]
set_property PACKAGE_PIN AB18 [get_ports {ddr4_sdram_dqs_c[1]}]
set_property PACKAGE_PIN AK22 [get_ports {ddr4_sdram_dqs_t[2]}]
set_property PACKAGE_PIN AK23 [get_ports {ddr4_sdram_dqs_c[2]}]
set_property PACKAGE_PIN AM21 [get_ports {ddr4_sdram_dqs_t[3]}]
set_property PACKAGE_PIN AN21 [get_ports {ddr4_sdram_dqs_c[3]}]
set_property PACKAGE_PIN AC12 [get_ports {ddr4_sdram_dqs_t[4]}]
set_property PACKAGE_PIN AD12 [get_ports {ddr4_sdram_dqs_c[4]}]
set_property PACKAGE_PIN AG9  [get_ports {ddr4_sdram_dqs_t[5]}]
set_property PACKAGE_PIN AH9  [get_ports {ddr4_sdram_dqs_c[5]}]
set_property PACKAGE_PIN AK8  [get_ports {ddr4_sdram_dqs_t[6]}]
set_property PACKAGE_PIN AL8  [get_ports {ddr4_sdram_dqs_c[6]}]
set_property PACKAGE_PIN AN9  [get_ports {ddr4_sdram_dqs_t[7]}]
set_property PACKAGE_PIN AN8  [get_ports {ddr4_sdram_dqs_c[7]}]

# DDR4 Data Mask
set_property PACKAGE_PIN AH22 [get_ports {ddr4_sdram_dm_n[0]}]
set_property PACKAGE_PIN AE18 [get_ports {ddr4_sdram_dm_n[1]}]
set_property PACKAGE_PIN AL20 [get_ports {ddr4_sdram_dm_n[2]}]
set_property PACKAGE_PIN AP19 [get_ports {ddr4_sdram_dm_n[3]}]
set_property PACKAGE_PIN AF11 [get_ports {ddr4_sdram_dm_n[4]}]
set_property PACKAGE_PIN AH12 [get_ports {ddr4_sdram_dm_n[5]}]
set_property PACKAGE_PIN AK13 [get_ports {ddr4_sdram_dm_n[6]}]
set_property PACKAGE_PIN AN12 [get_ports {ddr4_sdram_dm_n[7]}]

# DDR4 Reset
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVCMOS12 DRIVE 8} [get_ports {ddr4_sdram_reset_n}]

# GPIO Reset
set_property -dict {PACKAGE_PIN M11 IOSTANDARD LVCMOS33} [get_ports {CPU_RESET}]

# GPIO DIP Switch
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS33} [get_ports {GPIO_DIP_SW0}]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {GPIO_DIP_SW1}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {GPIO_DIP_SW2}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {GPIO_DIP_SW3}]

# GPIO LED
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {GPIO_LED_0_LS}]
set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS33} [get_ports {GPIO_LED_1_LS}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {GPIO_LED_2_LS}]
set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS33} [get_ports {GPIO_LED_3_LS}]

# GPIO Pushbutton
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {GPIO_PB_SW0}]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports {GPIO_PB_SW1}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {GPIO_PB_SW2}]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports {GPIO_PB_SW3}]

# FMC LPC
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la00_cc_n}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la00_cc_p}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la01_cc_n}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la01_cc_p}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la02_n}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la02_p}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la03_n}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la03_p}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la04_n}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la04_p}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la05_n}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la05_p}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la06_n}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la06_p}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la07_n}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la07_p}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la08_n}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la08_p}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la09_n}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la09_p}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la10_n}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la10_p}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la11_n}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la11_p}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la12_n}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la12_p}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la13_n}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la13_p}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la14_n}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la14_p}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la15_n}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la15_p}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la16_n}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la16_p}]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la17_cc_n}]
set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la17_cc_p}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la18_cc_n}]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la18_cc_p}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la19_n}]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la19_p}]
set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la20_n}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la20_p}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la21_n}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la21_p}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la22_n}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la22_p}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la23_n}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la23_p}]
set_property -dict {PACKAGE_PIN A6  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la24_n}]
set_property -dict {PACKAGE_PIN B6  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la24_p}]
set_property -dict {PACKAGE_PIN C6  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la25_n}]
set_property -dict {PACKAGE_PIN C7  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la25_p}]
set_property -dict {PACKAGE_PIN B8  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la26_n}]
set_property -dict {PACKAGE_PIN B9  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la26_p}]
set_property -dict {PACKAGE_PIN A7  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la27_n}]
set_property -dict {PACKAGE_PIN A8  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la27_p}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la28_n}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la28_p}]
set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la29_n}]
set_property -dict {PACKAGE_PIN K10 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la29_p}]
set_property -dict {PACKAGE_PIN D9  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la30_n}]
set_property -dict {PACKAGE_PIN E9  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la30_p}]
set_property -dict {PACKAGE_PIN E7  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la31_n}]
set_property -dict {PACKAGE_PIN F7  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la31_p}]
set_property -dict {PACKAGE_PIN E8  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la32_n}]
set_property -dict {PACKAGE_PIN F8  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la32_p}]
set_property -dict {PACKAGE_PIN C8  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la33_n}]
set_property -dict {PACKAGE_PIN C9  IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_la33_p}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_clk0_m2c_n}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS18} [get_ports {fmc_lpc_clk0_m2c_p}]
